UPDATE Date$
SET Date = DATEADD(YEAR, -4, Date)
WHERE YEAR(Date) = 2020;

UPDATE Date$
SET Year = 2016
WHERE YEAR = 2020;

UPDATE Date$
SET Date = DATEADD(YEAR, -4, Date)
WHERE YEAR(Date) = 2021;

UPDATE Date$
SET Year = 2017
WHERE YEAR = 2021;

UPDATE Date$
SET EOM = DATEADD(YEAR, -4, Date)
WHERE YEAR(EOM) = 2020;

UPDATE Date$
SET EOM = DATEADD(YEAR, -4, Date)
WHERE YEAR(EOM) = 2021;


