--Data Warehouse

--OLTP, OLAP

---OLTP -> Online transactional/transaction Process
-----OLAP -> Online Analytical/Anaysis Process....

--OLTP:

--1 ta transaction table majhkhane ar baki gula master table bairergula jegula conncet kora...
-- akhane continiously data update delete hocche....

--OLAP:
--fact tabl/ measure table ar bakigula baire dimension table
--ai measure table a sum max min calculation, profit loss ashob kaj hoy....
--ar je gula nie ke koethay oi table gula dimension table
--- who when where agula table gula dimension table ba short a dim table .....


--- 2 dhoroner design kora hoy akhane.....

---*** OLTP te number of table beshi thake ar OLAP te kom thake table.....

---akhane data shudhu read kori write korina.....
----******* production server hocche OLAP , akhan theke data then OLAP ba data warehouse a nie jacchi....
----*** amra oltp theke data warehouse a nie ashtesi mane olap a nie ashtesi analysis ar jonno dine akbar ba 2 barer jonno ba companyr upor depend kore.... ba hours ao update hoy...
----**** olap te shudhu read hocche arrr oltp the read and write 2 tai hocche.......


----OLTP te normalize data use kora hoy....

----OLAP te de normalize data use kora hoy...
--- duplicate table na korte hoy tai arekta tabe banai...
--- dept name jodi character hoy tahole slow kore felbe ar number hole slow korbena...

--- agular avabe dept alda tabe kore nie neya hoy....

-- ****shob table ane aktate korle then update delete hole onek sloq hoye jabe tai avabe alada table toiri kora....

----*** department ba location agua duplicate thakle amra alada aada kore table banate pari....
----****** table ar shonkha barabo jokhon data duplicate hoy tokhon.......
----**** ai repeat ba duplicate na olap te problem nai but oltp te problem tai oltp te alda kora...
----***OLAP te table ar shokha kom thake ar OLTP te beshi....

----*** Datawarehouse -> OLAP ---> ata proti hours a akhane ashe production tbl theke ba dine company wise...

----OLTP te data read and write 2 tai hocche ar OLAP te data shudhu read hocche....
----OLTP te normalize data use hoy, ar OLAP te de normalize data....
---normalize holo duplicate hobe na , ata OLTP te hoy, ar OLAP te duplicate hote parbe tai beshi table hoy...
----- OLAP te denormalize data ar OLTP te normalize data use hoy......
----- akta identity die dibo number die oi name ar bodle.....


-----*** amader 2ta db ache jemon-> adventureworks ota OLTP arrr adventureworksDW holo OLAP...

------adventureworks ta production server ar DW ta DataWarehouse...

------****** dw te ba OLAP te tabe ar shonkha kom thake ar dupicate hote parbe....
-----dw te dim table ar fact table ache.....
------ 1ta fact table a onekgula dim table connect kora amon.....
-----****** fact tabe a thake fk ar baki connected table guay thake pk tahole amra design korte parbo....

---fact a normayy number die kajta korbo....
----***** PowerBI te jeta banabo ota akhan thekei jabe mainly ai dim table gula thake....

-----**** person dim tble ta pk tai atay unique at oi fact tbl fk tai okhan eduplicate hobe... person ar id akta 1 hole fact table a jeye she 3bar kinle tar id okhane 1,1,1 hobe......
-----****OLTP -> bank bar ecommerce site hote par ba aro kichu....
----**** It involves with ETL(Extraction, Transformation and Loading)   , desinged for analytical and repoting purpose....
----*** normalization a repeat data hole oguake akta kora jate repeat na hoy tai normalize bole 
---* denormalize holo repeat hobe olap te ba duplicate....
----*****denormalize kore data take dw a neya asha jay...
-----***** normalize-> a duplicate remove kore onekgula table banano hoy....


---- ***** dhori 7 ta tbl akshathe ase oita hocche denormalize ar alda korle akekta then normalize korlam....



----****** normalize holo production ar belay.....


-----**** analaysis ar shomoy tbl ar shokha komaite pari tokhon olap te,..... komano manei duplicate value akshathe merge kora...
-------**** Data warehouse Modeling:
----*** ETL developer/DW developer ader kaj source theke destination a a data ana....


----*** 2 ta table theke 1 table banano manei merge kora bole... ETL process a transform a.....

----*** OLTP ba production data deya hobe ota akta tool ar maddhome change kore then OLAP te ba DW te nibo amra......

---- ******sql server ar tool SSIS jeta die merge kora data ba split kora jay....
----- ETL process a SSIS ar kajta hoy.....

----WIlliam bolse age dw te nie then amra data take subject onujayi alada aalada kore file/db banabo....
----***** DATA MART: hocche data take separate kora subject onujayi ba alda db toiri kora , DW ae age ba pore.......
----Data mart akta database ar moto....
----*** based on dim and fact table 2 types of design was created: Star Schema and Snow Flake Schema...
----***** aita porchi data warehouse modeling theke:
----**** Star schema: dimension tables are directy connected to fact table...
-----Snow flake schema: jodi 1 or more table are indirectly connected to the fact table....
----*** employee table ar oita ak prokar snow flake schema......

----normally je data thake normalize kora thake ar amra analysis ar shomoy de normalize kore kaj korbo....

























































